import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import Navigation from "./components/navigation/index.client";
import "./globals.css";
import { Providers } from "./providers";

const noto = Noto_Sans({

 subsets: ["latin"],
 variable: "--font-noto-sans",
 weight: ['400', '700'],
 display: "swap",
});

export const metadata: Metadata = {
  title: "Bio Design Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${noto.variable} font-noto-sans`}>
      <Providers>
        <body>

          <Navigation />
          {children}
        </body>
      </Providers>
    </html>
  );
}
