import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from "./components/navigation/index.client";
import Carrousel from './components/ModuleCustom/carrousel/page';
import ModuleCustomLayout from './components/ModuleCustom/layout';
import FooterLayout from './components/footer/layout';
import Footer from './components/footer/page';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
         {/* Metadata and other head elements */}
      </head>
      <body>
        <Navigation></Navigation>
        {children}
        <Footer></Footer>

      </body>
    </html>
  )
}
